# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_fpaths": "02_read_data.ipynb",
         "read_files": "02_read_data.ipynb",
         "parse_dates": "02_read_data.ipynb"}

modules = ["read_data.py"]

doc_url = "https://wuqui.github.io/socembed/"

git_url = "https://github.com/wuqui/socembed/tree/master/"

def custom_doc_links(name): return None
