# AUTOGENERATED! DO NOT EDIT! File to edit: 02_read_data.ipynb (unless otherwise specified).

__all__ = ['get_fpaths', 'read_files', 'parse_dates']

# Cell
from glob import glob
import pandas as pd

# Cell
def get_fpaths(LEX, CORPUS_DIR='/Volumes/qjd/promo/SocEmb/data/psaw/'):
    lex_path = f'{CORPUS_DIR}{LEX}' + "/*.csv"
    fpaths = glob(lex_path)
    return fpaths

# Cell
def read_files(fpaths):
    dfs = []
    for fp in fpaths:
        df = pd.read_csv(
            fp,
            usecols=['id', 'created_utc', 'subreddit', 'body'],
        )
        dfs.append(df)
    df = pd.concat(
        dfs,
        axis=0,
        ignore_index=True
    )
    return df

# Cell
def parse_dates(df):
    df['created_utc'] = pd.to_datetime(df['created_utc'], errors='coerce')
    df.sort_values('created_utc', inplace=True)
    df.dropna(subset=['created_utc'], inplace=True)
    return df