# AUTOGENERATED! DO NOT EDIT! File to edit: 02_read_data.ipynb (unless otherwise specified).

__all__ = ['get_fpaths']

# Cell
from glob import glob

# Cell
def get_fpaths(LEX, CORPUS_DIR='/Volumes/qjd/promo/SocEmb/data/psaw/'):
    lex_path = f'{CORPUS_DIR}{LEX}' + "/*.csv"
    fpaths = glob(lex_path)
    return fpaths