# AUTOGENERATED! DO NOT EDIT! File to edit: 05_usage_intensity.ipynb (unless otherwise specified).

__all__ = ['get_monthly_freq', 'plot_use_freq']

# Cell
import pandas as pd
import altair as alt

# Cell
def get_monthly_freq(df):
    df_m = (df
     .loc[:, ['id', 'created_utc']]
     .groupby(pd.Grouper(key='created_utc', freq='M'))
     .agg(comm_n = ('id', 'count'))
     .reset_index()
     .rename({'created_utc': 'month'}, axis=1)
    )

    # remove first and last month to ensure we're only considering complete months
    # could be removed if we're using rolling mean for visualization -> preferable
    df_m = df_m.iloc[1:-1]

    return df_m

# Cell
def plot_use_freq(df_m, LEX):
    chart = alt.Chart(df_m)\
        .mark_line(point=True)\
         .encode(
             x=alt.X('month:T', title=''),
             y=alt.Y('comm_n:Q', title='comments / month')
         )\
         .properties(title=LEX)\
         .interactive()
    return chart